name: Build and Publish Devcontainer (Rust)

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hautechai/devcontainer-universal
  GLIBC_MIN: "2.34"

jobs:
  build:
    runs-on: ubuntu-latest-8-core-public
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=stable,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,format=short,prefix=sha-
            type=raw,value={{date 'YYYYMMDD'}},enable=${{ github.ref == 'refs/heads/main' }}
          labels: |
            org.opencontainers.image.title=devcontainer-universal (Rust)
            org.opencontainers.image.description=Universal DevContainer extended with Rust toolchain and common native deps.

      - name: Build (PR smoketest)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: smoketest
          push: false
          load: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Smoke tests (main; remote image, root)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stable
          docker pull ${IMAGE}
          docker run --rm ${IMAGE} bash -lc 'set -euo pipefail; rustc --version; cargo --version; rustfmt --version; cargo clippy -V; command -v rg && rg --version; command -v doppler && doppler --version; test -d "$PLAYWRIGHT_BROWSERS_PATH" && [ -n "$(ls -A "$PLAYWRIGHT_BROWSERS_PATH")" ]'
          docker run --rm -e GLIBC_MIN="${{ env.GLIBC_MIN }}" ${IMAGE} bash -lc 'set -euo pipefail; ldd --version; v=$(getconf GNU_LIBC_VERSION | cut -d" " -f2); echo "glibc=$v (min=${GLIBC_MIN})"; dpkg --compare-versions "$v" ge "${GLIBC_MIN}" || { echo "ERROR: glibc < ${GLIBC_MIN}"; exit 1; }'

